---
development:
  cloud_name: theprivatepark
  api_key: '225698276297125'
  api_secret: fxzugqPGV2TSbMNASJWb_mfsuas
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: theprivatepark
  api_key: '225698276297125'
  api_secret: fxzugqPGV2TSbMNASJWb_mfsuas
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: theprivatepark
  api_key: '225698276297125'
  api_secret: fxzugqPGV2TSbMNASJWb_mfsuas
  enhance_image_tag: true
  static_file_support: false
